name: booness
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:

  awesome_notifications: ^0.9.3+1
  expansion_tile_card: ^3.0.0
  animated_text_lerp: ^1.0.5
  cloud_firestore:
  banner_carousel: ^1.2.1
  provider:
  image_picker:
  firebase_storage:
  cupertino_icons:
  custom_refresh_indicator:
  highlightable: ^1.0.5
  dart_image_slider:
  easy_rich_text:
  file_picker:
  firebase_auth:
  firebase_core:
  firebase_database:
  app_bar_with_search_switch:
  flutter_image_compress: ^2.3.0
  easy_draggable: ^0.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager:
  flutter_phosphor_icons:
  flutter_quill: ^9.3.10
  google_fonts:
  gallery_saver: 
  path_provider: 
  path:
  url_launcher:
  gif_view: 
  sqflite:
  google_sign_in:
  image:
  intl: ^0.19.0
  adaptive_theme: ^3.6.0
  animate_do:
  page_transition:
  restart_app: ^1.1.3
  staggered_grid_view_flutter:
  confetti: ^0.7.0
  vibration: ^1.9.0
  encrypt: ^5.0.3
  
  crypto: any
dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/onboarding/
    - assets/onboarding/00.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
