// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjlMBnRl09ld30ny6smrFhI6k-aVa81qM',
    appId: '1:61474647326:web:4629082b50efd3b7102d0f',
    messagingSenderId: '61474647326',
    projectId: 'dailygoodness-ad11f',
    authDomain: 'dailygoodness-ad11f.firebaseapp.com',
    databaseURL: 'https://dailygoodness-ad11f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dailygoodness-ad11f.appspot.com',
    measurementId: 'G-P5Q8Y9CKTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiGZh5XtzqM1aKhXK54_TKvdcXsQffq78',
    appId: '1:61474647326:android:93ada924fcf7cbe4102d0f',
    messagingSenderId: '61474647326',
    projectId: 'dailygoodness-ad11f',
    databaseURL: 'https://dailygoodness-ad11f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dailygoodness-ad11f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcvX6lA744Mw_5wmxxSZfvBbcVcfecU4k',
    appId: '1:61474647326:ios:0cb1294275fc5e69102d0f',
    messagingSenderId: '61474647326',
    projectId: 'dailygoodness-ad11f',
    databaseURL: 'https://dailygoodness-ad11f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dailygoodness-ad11f.appspot.com',
    iosClientId: '61474647326-52lnjlfe9a47q605bthtsea4sj2u6il1.apps.googleusercontent.com',
    iosBundleId: 'com.example.booness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcvX6lA744Mw_5wmxxSZfvBbcVcfecU4k',
    appId: '1:61474647326:ios:87cb65f70b5be60a102d0f',
    messagingSenderId: '61474647326',
    projectId: 'dailygoodness-ad11f',
    databaseURL: 'https://dailygoodness-ad11f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dailygoodness-ad11f.appspot.com',
    iosClientId: '61474647326-i76pssdbhpo8hsv7avcflcg7eqbuvfl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.booness.RunnerTests',
  );
}
